version: 2
updates:
  - package-ecosystem: npm
    directory: "/toolknit-desktop"
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: "/toolknit-desktop/cli"
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5

  - package-ecosystem: cargo
    directory: "/toolknit-desktop/src-tauri"
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5
