import { toolTopbarMarkup } from '../../shared/tool-page-shell.js';

export function imageColorReplaceTemplate() {
  return `<div class="tool-page-v2-shell color-replace-shell">
    ${toolTopbarMarkup({ tag: 'IMAGE TOOLS · TOOL PAGE 3.1', title: '智能颜色替换', closeAttr: 'data-cr-close' })}
    <main class="tool-page-v2-body color-replace-main">
      <aside class="tool-page-v2-rail color-replace-rail">
        <div class="tool-page-v2-rail-kicker">IMAGE COLOR REPLACER</div><h1>智能颜色<br>替换</h1><p>用感知色差和连通区域精准替换图像颜色，保留边缘与明暗层次。</p>
        <div class="tool-page-v2-rail-note"><span>LOCAL ONLY</span><strong>原图不会上传服务器，最终导出始终从原始分辨率处理。</strong></div>
        <div class="tool-page-v2-steps"><div class="is-active"><b>01</b><span><strong>导入图片</strong><small>选择 PNG、JPG、WebP 或 BMP。</small></span></div><div><b>02</b><span><strong>取样颜色</strong><small>在画布中点击需要替换的像素。</small></span></div><div><b>03</b><span><strong>调整保护</strong><small>控制阈值、柔化和主体保护。</small></span></div><div><b>04</b><span><strong>导出结果</strong><small>由原图生成高质量输出文件。</small></span></div></div>
      </aside>
      <section class="color-replace-stage-section"><div class="color-replace-stage-head"><div><span>LIVE CANVAS</span><strong data-cr-file>等待载入图片</strong></div><div class="color-replace-stage-actions"><button type="button" data-cr-compare disabled><i data-lucide="scan-eye"></i><span>按住查看原图</span></button><button type="button" data-cr-pick><i data-lucide="image-plus"></i><span>选择图片</span></button><button class="color-replace-export" type="button" data-cr-export disabled><i data-lucide="download"></i><span>导出原图</span></button></div></div>
        <div class="color-replace-stage tk-vertical-stripe-surface" data-cr-stage><button class="color-replace-empty tk-empty-hero" type="button" data-cr-pick><span class="tk-empty-hero-icon"><i data-lucide="pipette"></i></span><span class="tk-empty-hero-kicker">LOCAL COLOR WORKSPACE</span><strong>从一个像素开始</strong><span class="tk-empty-hero-description">选择图片，再用吸管点击需要替换的颜色</span><em><i data-lucide="upload"></i><span>选择图片</span></em></button><canvas data-cr-canvas></canvas><div class="color-replace-busy" data-cr-busy hidden><span></span><strong>正在分析像素...</strong></div></div>
        <div class="color-replace-stage-footer"><span data-cr-meta>PNG / JPG / WebP / BMP</span><label><i data-lucide="zoom-in"></i><input type="range" min="50" max="300" value="100" data-cr-zoom><output data-cr-zoom-value>100%</output></label></div>
      </section>
      <aside class="color-replace-controls">
        <section><div class="color-replace-section-head"><span>01 / SAMPLE</span><strong>取样与目标色</strong></div><div class="color-pair"><button type="button" data-cr-eyedropper class="is-active"><i data-lucide="pipette"></i><span><small>源颜色</small><b data-cr-source-label>#FFFFFF</b></span><i class="color-swatch" data-cr-source-swatch></i></button><span class="color-pair-arrow" aria-hidden="true"><i data-lucide="arrow-right"></i></span><label class="color-target-picker"><i data-lucide="palette"></i><span><small>目标颜色</small><b data-cr-target-label>#2D7AD2</b></span><i class="color-swatch" data-cr-target-swatch></i><input type="color" value="#2D7AD2" data-cr-target></label></div><p class="color-replace-hint">吸管会同时记录像素颜色和连通区域起点。</p></section>
        <section><div class="color-replace-section-head"><span>02 / TOLERANCE</span><strong>替换范围</strong></div><label class="color-replace-range"><span><b>颜色阈值</b><output data-cr-threshold-value>20</output></span><input type="range" min="1" max="80" value="20" data-cr-threshold><small>数值越大，会包含更多相近颜色。</small></label><label class="color-replace-range"><span><b>边缘柔化</b><output data-cr-softness-value>24%</output></span><input type="range" min="0" max="100" value="24" data-cr-softness><small>只在阈值边缘建立轻微过渡。</small></label></section>
        <section><div class="color-replace-section-head"><span>03 / PROTECTION</span><strong>主体保护</strong></div><label class="color-replace-toggle"><span><b>智能保护</b><small>只替换吸管起点所在的八连通区域</small></span><input type="checkbox" checked data-cr-smart><i></i></label><label class="color-replace-toggle"><span><b>保留明暗层次</b><small>把原区域的亮度变化带入新颜色</small></span><input type="checkbox" checked data-cr-luminance><i></i></label><div class="color-replace-warning" data-cr-warning hidden><i data-lucide="triangle-alert"></i><span>智能保护已关闭，所有相近像素都会被替换。</span></div></section>
        <section><div class="color-replace-section-head"><span>04 / OUTPUT</span><strong>导出设置</strong></div><div class="color-replace-format" data-cr-formats><button class="is-active" data-format="png">PNG</button><button data-format="jpg">JPG</button><button data-format="webp">WEBP</button><button data-format="bmp">BMP</button></div><label class="color-replace-quality" data-cr-quality hidden><span>JPG 质量 <output data-cr-quality-value>92</output></span><input type="range" min="50" max="100" value="92" data-cr-quality-input></label><div class="color-replace-history"><button type="button" data-cr-undo disabled><i data-lucide="undo-2"></i><span>撤销</span></button><button type="button" data-cr-reset disabled><i data-lucide="rotate-ccw"></i><span>重置</span></button></div></section>
      </aside>
    </main>
  </div>`;
}
